multidadosti-erp/multidadosti-addons

- .travis.yml
- admin_development_features/__init__.py
- admin_development_features/__manifest__.py
- admin_development_features/views/res_groups.xml
- disable_suport_footer/__init__.py
- disable_suport_footer/__manifest__.py
- disable_suport_footer/views/view_disable_suport_footer.xml
- oca_dependencies.txt
Módulo disable_suport_footer que permite instalar outros temas junto com a localização
> [NEW] Modulo disable_suport_footer

- disable_powered_odoo_footer/__manifest__.py
- disable_powered_odoo_footer/views/view_disable_powered_odoo_footer.xml
Mudanças:
-Adequação do xml da view para odoo 10.0
-Adequação da 'div de substituição' para odoo 10.0
> Adequação do módulo de desabilitação do footer para uso no odoo 10.0

- custom_group_postit/__init__.py
- custom_group_postit/__manifest__.py
- custom_group_postit/i18n/pt_BR.po
- custom_group_postit/views/view_custom_group_postit.xml
Agrupamento do Post-it, Mensagens e Calendario
*-(Alguns labels ou menus não sofrem alteração, ou não são totalmente modificados após a instalação do módulo, para essas mudanças é necessário modificar manualmente através do caminho Configurações -> Técnico -> Interface de Usuário -> Itens de Menu)*
> Criação de módulo para agrupar aplicativos

- custom_group_postit/views/view_custom_group_postit.xml
Possibilidade de criar novos marcadores a partir da tela de formulario no módulo post-it
> [IMP] Adicionada opção de criar novos marcadores em *Post-it*

- block_crm_quotation_for_stage/__manifest__.py
- block_crm_quotation_for_stage/views/res_partner_views.xml
- block_crm_quotation_for_stage/views/sale_views.xml
- project_task_calendar/i18n/pt_BR.po
- project_task_calendar/models/calendar.py
- project_task_calendar/views/view_calendar.xml
- project_task_calendar/views/view_project_project.xml
- project_task_calendar/wizard/wizard_calendar_event_done.xml
> [FEATURE] Custom(crm, project, calendar, sale_order)

- general_views_customize/__manifest__.py
- general_views_customize/i18n/pt_BR.po
- general_views_customize/views/res_partner_view.xml
Campo busca por partners que não sejam clientes ou fornecedores. inclusão de respectiva tradução do filtro também.
fixex #119
> [IMP] Inclusão de filtro para propostas

- project_task_calendar/i18n/pt_BR.po
- project_task_calendar/views/view_project_project.xml
> [FIX]Correção do menu de calendários na tela de projetos

- project_related_partners/views/project_project.xml
> [IMP] Campo partner_id de project.project passa a ser obrigatório

- account_financial_operation_and_title_type/models/account_title_type.py
- account_financial_operation_and_title_type/views/account_title_type.xml
Ajuste no campo preço mínimo de float para currency
close https://github.com/multidadosti-erp/erp-project/issues/19
> [FIX]Ajuste no campo preço mínimo de float para currency

- base_product_type_expense/i18n/pt_BR.po
- base_product_type_expense/views/product_template.xml
close https://github.com/multidadosti-erp/erp-project/issues/22
> [Feature] Refatoramento de view em product.template

- helpdesk_phonecall_support/i18n/pt_BR.po
- helpdesk_phonecall_support/models/helpdesk_phonecall_service.py
- helpdesk_phonecall_support/views/helpdesk_phonecall_service.xml
close https://github.com/multidadosti-erp/erp-project/issues/29
> [NEW] Adicionado campo 'external_code' em 'helpdesk_phonecall_support'

- hr_timesheet_project_task_stage/views/project_task.xml
fix https://github.com/multidadosti-erp/erp-project/issues/32
> [FIX] Erro Object has no attribute 'company_id' em Tarefas do Projeto

- helpdesk_phonecall_support/models/helpdesk_phonecall_service.py
- helpdesk_phonecall_support/views/helpdesk_phonecall_service.xml
- helpdesk_phonecall_support/wizards/helpdesk_phonecall_confirm.py
- helpdesk_phonecall_timesheet/__manifest__.py
- helpdesk_phonecall_timesheet/i18n/pt_BR.po
- helpdesk_phonecall_timesheet/wizards/helpdesk_phonecall_confirm.py
- hr_timesheet_base_partner_company/__init__.py
- hr_timesheet_base_partner_company/__manifest__.py
- hr_timesheet_base_partner_company/models/__init__.py
- hr_timesheet_base_partner_company/models/account_analytic_line.py
- hr_timesheet_base_partner_company/views/account_analytic_line.xml
- hr_timesheet_project_task_stage/i18n/pt_BR.po
Criado campo relacional da 'helpdesk.phonecall.service' para 'account.analytic.line' para o campo 'partner_id'
close https://github.com/multidadosti-erp/erp-project/issues/33
> Erro ao Gravar o Cliente vindo do Módulo de Atendimento

- base_partner_skype/views/res_partner.xml
close https://github.com/multidadosti-erp/erp-project/issues/46
> [FIX]Correção no módulo 'base_partner_skype' efetuada ao criar contato

- project_task_count_calendar_event/i18n/pt_BR.po
- project_task_count_calendar_event/models/project_project.py
close https://github.com/multidadosti-erp/erp-project/issues/42
> [REF]Tradução das palavras do Kanban de projeto

- project_planned_time/__manifest__.py
- project_planned_time/i18n/pt_BR.po
- project_planned_time/models/project_project.py
- project_planned_time/views/project_project.xml
close https://github.com/multidadosti-erp/erp-project/issues/56
> Informar no Cadastro do Projeto o Comparativo de Horas

- crm_lead_is_customer/i18n/pt_BR.po
- crm_lead_is_customer/views/crm_lead.xml
close https://github.com/multidadosti-erp/erp-project/issues/96
> [FIX]Adicionar Filtro ARQUIVADO

- mail_custom_permission_message/i18n/pt_BR.po
close https://github.com/multidadosti-erp/erp-project/issues/99
> [FIX]Traduzir Tela de Caixa de Entrada - Dica

- calendar_event_stage/i18n/pt_BR.po
- calendar_event_stage/views/calendar_event.xml
close https://github.com/multidadosti-erp/erp-project/issues/95
> [REF]Destacar no Calendário Eventos Cancelados

- base_product_type_expense/views/product_template.xml
close https://github.com/multidadosti-erp/erp-project/issues/108
> [REF]Campo NCM da fatura invisível para serviços

- calendar_event_stage/i18n/pt_BR.po
- calendar_event_stage/views/calendar_event.xml
close https://github.com/multidadosti-erp/erp-project/issues/107
> [REF]Mudar a Dica da Inclusão da Agenda

- account_replace_invoice_menu/i18n/pt_BR.po
close https://github.com/multidadosti-erp/erp-project/issues/102
> [REF]Renomear menu "Contabilidade" para "Financeiro"

- web_custom_dashboard/static/src/xml/dashboard.xml
close https://github.com/multidadosti-erp/erp-project/issues/105
> [REF]Remover botões de Twitter, Facebook e Linkedin

- base_partner_is_not_customer/models/__init__.py
- base_partner_is_not_customer/models/res_partner.py
- base_partner_is_not_customer/views/res_partner.xml
No cadastro de cliente deixei o campo 'parent_id' invisible e o  campo 'company_type' default 'company'
close https://github.com/multidadosti-erp/erp-project/issues/110
> [FIX] Acerto no Cadastro do Cliente conforme Imagem em Anexo

- helpdesk_phonecall_support/security/ir.model.access.csv
close https://github.com/multidadosti-erp/erp-project/issues/126
> [REF]Manutenção no arquivo csv , afim de deixar o lider excluir chamados

- calendar_event_file_attachment/models/project_project.py
- oca_dependencies.txt
close https://github.com/multidadosti-erp/erp-project/issues/118
> Corrigir metodo 'attachment_tree_view' 

- project_task_partner_customize/models/project_task.py
close https://github.com/multidadosti-erp/erp-project/issues/137
> Tarefa do Projeto enviar msg (semelhante ao postit)

- project_attachment_tags/i18n/pt_BR.po
- project_attachment_tags/models/ir_attachment.py
close https://github.com/multidadosti-erp/erp-project/issues/142
close https://github.com/multidadosti-erp/erp-project/issues/138
> Manutenção no método de inclusão de anexos e atualização da tradução

- account_replace_invoice_menu/views/account_replace_invoice_menu.xml
close https://github.com/multidadosti-erp/erp-project/issues/154
> Esconder menu "Cotação" e "Pedido de Venda"

- account_payment_project/i18n/pt_BR.po
- account_payment_project/views/account_payment.xml
- general_payments/i18n/pt_BR.po
- general_payments/views/account_payment.xml
close https://github.com/multidadosti-erp/erp-project/issues/172
> Ajustes modulo Pagamento Avulso

- project_task_partner_customize/views/project_project.xml
close https://github.com/multidadosti-erp/erp-project/issues/174
> Deixar campo "Privacidade" invisível na tela de projeto

- helpdesk_phonecall_support/views/helpdesk_phonecall_service.xml
close https://github.com/multidadosti-erp/erp-project/issues/185
> Consertar filtro 'Hoje' de helpdesk.phonecall.suport'

- base_product_type_expense/views/product_template.xml
close https://github.com/multidadosti-erp/erp-project/issues/193
> Configuração Partner - Multi Company

- account_replace_invoice_menu/__manifest__.py
- account_replace_invoice_menu/views/account_replace_invoice_menu.xml
Escondi alguns menus na tela do financeiro.
https://github.com/multidadosti-erp/erp-project/issues/197
> Develop replace menu account

- base_partner_is_not_customer/views/res_partner.xml
close https://github.com/multidadosti-erp/erp-project/issues/215
> Campo com nome do partner está estourando quando a janela é um pop up

- project_default_stages/views/project_project.xml
- project_kanban_onclick_redirect_project/views/project_project.xml
close https://github.com/multidadosti-erp/erp-project/issues/163
> Ao criar projeto, mover o usuário direto para a tela de projeto

- base_partner_is_not_customer/models/res_users.py
close https://github.com/multidadosti-erp/erp-project/issues/201
> Modulo base_user_from_partner esta causando erro ao criar novo usuario

- helpdesk_phonecall_support/models/helpdesk_phonecall_service.py
- helpdesk_phonecall_support/tests/__init__.py
- helpdesk_phonecall_support/tests/test_helpdesk_phonecall_confirm.py
- helpdesk_phonecall_support/tests/test_helpdesk_phonecall_service.py
close https://github.com/multidadosti-erp/erp-project/issues/227
> Horario de atendimento dica alterando toda hora

- web_custom_login_page/templates/web.xml
- web_set_title_page/templates/web.xml
close https://github.com/multidadosti-erp/erp-project/issues/225
> Verificar os modulos web do multidados addons e substitui por modulos da OCA 

- crm_lead_is_customer/i18n/pt_BR.po
- crm_lead_is_customer/models/crm_lead.py
- crm_lead_is_customer/views/crm_lead.xml
- crm_postit/models/crm_lead.py
- crm_postit/views/crm_lead_views.xml
- crm_postit/views/postit_view.xml
close https://github.com/multidadosti-erp/erp-project/issues/237
> Alterações no cadastro de Oportunidades

- account_replace_invoice_menu_sale/views/sale.xml
close https://github.com/multidadosti-erp/erp-project/issues/231
> Tornar menu de cotação presente em vendas visível novamente

- helpdesk_phonecall_support/i18n/pt_BR.po
- helpdesk_phonecall_support/models/helpdesk_phonecall_service.py
- helpdesk_phonecall_support/views/helpdesk_phonecall_service.xml
> Incluir no Módulo de Atendimento

- project_partner_menu_in_project/i18n/pt_BR.po
- project_partner_menu_in_project/views/res_partner.xml
- project_quality_classification/models/project_task.py
1. Mudar a Tradiução de CLIENTE para CLIENTES
2. Ao clicar nos CLIENTES, ao chamar a tela passar já o filtro de CLIENTES
> Acerto Menu dos Projetos

- base_partner_is_not_customer/__manifest__.py
- base_partner_is_not_customer/views/res_users.xml
Depende de https://github.com/multidadosti-erp/odoo-brasil-addons/pull/22
> [NEW] Alterado css do botao de alterar senha da tela de preferencias

- project_task_set_default_filter/views/project_task.xml
**1. Criar baseado no Módulo da Trust-Code**
https://github.com/Trust-Code/trustcode-addons/tree/10.0/project_task_report
>  **_R: Módulo já estava incluso em nosso repositório, permitindo a impressão da tarefa_**
**2. Incluir no Pesquisa por Conteudo das Tarefas**
https://github.com/Trust-Code/trustcode-addons/tree/10.0/project_task_search_custom
> **_R: Módulo apenas adicionado um filtro_domain na view, adaptamos para o módulo 'project_task_set_default_filter'._**
**> Alteração no filtro nas Tarefas,para pesquisar a palavra pesquisa no nome, descrição ou mensagem**
>  Criar Relatório das Tarefas

- account_move_backup/models/account_invoice.py
- account_move_backup/security/ir.model.access.csv
- general_payments/views/account_move.xml
- Alterações em Formulário de Account Move Line
- Alteração em segurança do módulo de backup de Account Move Line
> Ajustes em módulos relacionados ao finânceiro
